#!/usr/bin/perl
use strict;
#use warnings;
#####################CAT
#>M01015:70:000000000-B45YW:1:1101:18781:1795 2:N:0:ACTCGCTA+AAGGAGTA
#CACCAGCTCCTCCATCTTCTCTTCAGCCCTGCTAGCGCCGGGAGCCCGCCCCCGAGAGGTGGGCTGCGGGTGTTTGAGGTCCAGCCGCCGCCGCCCGCGCTTGCCGTCGGCCCGTCGCCCGCTCAGAGGCGGCCCTCCACCGGAAGTGACACCGAACCGGGGCTGAGCGCCTCACTGCGGCCCCACCCCCGGCCCCCTTCGGGGGTGAACCCTGAAACCACGTCCCGCGCTCCACGCGGTTCCCTGTC
#############
#1   gacctgataa agattaacca gaagaaaaca aggagggaaa caaccgcagc ctgtagcaag
#61  ctctggaact caggagtcgc gcgctagggg ccggggccgg ggccggggcc ggggccgggg
#121 cgtggtcggg gcgggcccgg gggcgggccc ggggcggggc tgcggttgcg gtgcctgcgc
#181 ccgcggcggc ggaggcgcag gcggtggcga gtgggtgagt gaggaggcgg catcctggcg
#241 ggtggctgtt tggggttcgg ctgccgggaa gaggcgcggg tagaagcggg ggctctcctc
#301 agagctcgac gcatttttac tttccctctc atttctctga
#>M01015:70:000000000-B45YW:1:1101:17624:1738 2:N:0:AAGAGGCA+CTCTCTAT
#GACCTGATAAAGATTAACCCGATGAAACCAAGAAGGGAAACAACCACAGCCTGTAGCAAGCTCTGGAACTCAGGAGTCGCGCGCTCAAGGCCATGACCAGAACCAAAACCAGGGCCGAGGCGTGGTCGGGGCGGCCCCGGGAGCAGGCCCTGGGCGGGGCTGCGGGTGCCGGCCCCTCGCCCCCGGCGGCGCGGGCGCCGGCGGCGGCGGTGGGGGGCGGGGTGCGGGGGCGTTCTCGCCGGGCGTTTGT
#>M01015:70:000000000-B45YW:1:1101:17640:1770 2:N:0:AAGAGGCA+CTCTCTAT
#GCCCTGATACCGCTTAACAGCCGCAAACAAGGAGGGACACAACCGCAGCCTGTCGCAAGCTCTGCACCTCAGGAGTCGCGCCCTACAACCCCGGCCCGACACCCGGGCCGCGGCCCGGCCGTCATCAAAACGGCCCCGCCCACGCGCCCCCAACGCGGCTCCGGTTCCCATACCCCCCCCCCCCGCCGCGCCGGCGCAGCCGGCGGCCCGCCGCGCGCCGCCCCGCCGCCCCCCGCGCCGCGGCCCCGC
#####################
############################## 
##############maybe need to make a foreach for all lanes
my $in= "/cs/cbio/oren/SequencingData/Hagar/Hagar2_sense8.txt";
#>M01015:70:000000000-B45YW:1:2112:15114:9482 2:N:0:ACTCGCTA+AAGGAGTA
#CACCAGCTCCTCCATCTTCTCTTCAACCCTACTAACACCAAAAACCCACCCCCAAAAAATAAACTACAAACACTCAAAACCCAACCACCACCGCCGCCGCCGCCGCCACCACCCTACCACACACCCCCTAACAACAACACCTCCACCACCACCACCACCCACACCCACCACCAACCCCCCACCCACCCAAAAAAAACCCCCCCCAAAAAGCGAACCCACAACAGACCACAACCACACAAACAACCCAAA
#>M01015:70:000000000-B45YW:1:2101:9672:16694 2:N:0:ACTCGCTA+AAGGAGTA
#CACCAGCTCCTCCATCTTCTCTTCAGCCCTGCTAGCGCCGGGAGCCCGCCCCCGAGAGGTGGGCTGCGAGCGCTCGAGACCCAGCCGCCGCCGCCACCACCACCACCACCACCACACTACCCCCCCCCCCCTAACCACAACACCTCCATCACCCCCACCACCACACCCACCACCAACCCACCCCACACCCAAAAACAACCCCCCACCCACAGCGACACACAACACGCGCAGACCCCCCCCACCAGACAAA
#########################################################################
#my $ref="CACCAGCTCCTCCATCTTCTCTTCAGCCCTGCTAGCGCCGGGAGCCCGCCCCCGAGAGGTGGGCTGCGGGCGCTCGAGGCCCAGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCGCTGCCGCACGCCCCCTGGCAGCGGCGCCTCCGTCACCGCCGCCGCCCGCGCTCGCCGTCGGCCCGCCGCCCGCTCAGAGGCGGCCCTCCACCGGAAGTGAAACCGAAACGGAGCTGAGCGCCTGACTGAGGCCG";
#my $ref="CACCAGCTCCTCCATCTTCTCTTCAGCCCTGCTAGCGCCGGGAGCCCGCCCCCGAGAGGTGGGCTGCGGGCGCTCGAGGCCCAGCCGCCGCCGCCGCCGCCGCCGCCGCCGCCGCGCTGCCGCACGCCCCCTGGCAGCGGCGCCTCCGTCACCGCCGCCGCCCGCGCTCGCCGTCGGCCCGCCGCCCGCTCAGAGGCGGCCCTCCACCGGAAGTGAAACCGAAACGGAGCTGAGCGCCTGACTGAGGCC";
my $ref="CACCAGCTCCTCCATCTTCTCTTCAGCCCTGCTAGCGCCGGGAGCCCGCCCCCGAGAGGTGGGCTGCGGGCGCTCGAGGCCCAGCCGCCGCCGCCGCCGCCGCCGCCGCGCTGCCGCACGCCCCCTGGCAGCGGCGCCTCCGTCACCGCCGCCGCCCGCGCTCGCCGTCGGCCCGCCGCCCGCTCAGAGGCGGCCCTCCACCGGAAGTGAAACCGAAACGGAGCTGAGCGCCTGACTGAGGCC";
#my $ref="GACCTGATAAAGATTAACCAGAAGAAAACAAGGAGGGAAACAACCGCAGCCTGTAGCAAGCTCTGGAACTCAGGAGTCGCGCGCTAGGGGCCGGGGCCGGGGCCGGGGCCGGGGCCGGGGCGTGGTCGGGGCGGGCCCGGGGGCGGGCCCGGGGCGGGGCTGCGGTTGCGGTGCCTGCGCCCGCGGCGGCGGAGGCGCAGGCGGTGGCGAGTGGGTGAGTGAGGAGGCGGCATCCTGGCGGGTGGCTGTT";
#my $ref="GACCTGATAAAGATTAACCAGAAGAAAACAAGGAGGGAAACAACCGCAGCCTGTAGCAAGCTCTGGAACTCAGGAGTCGCGCGCTAGGGGCCGGGGCCGGGGCGTGGTCGGGGCGGGCCCGGGGGCGGGCCCGGGGCGGGGCTGCGGTTGCGGTGCCTGCGCCCGCGGCGGCGGAGGCGCAGGCGGTGGCGAGTGGGTGAGTGAGGAGGCGGCATCCTGGCGGGTGGCTGTTTGGGGTTCGGCTGCCGGG";
my @ref=split("",$ref);
##########################################################################
open IN,"<$in";
my %hash;	
my $line=<IN>; chomp $line;
while (defined($line)){
	if($line=~ m/^(\>.+)/){
		#print $line."\n";
		my $head=$1;
		$line=<IN>; chomp $line;
		$hash{$head}=$line;
		#print $line."\n";
		$line=<IN>; chomp $line;
	}	
	
}
close(IN); 
print "end loading\n";
my $out= "/cs/cbio/oren/SequencingData/Hagar/Hagar2_sense8_conv_tab.txt";
open OUT,">$out";
my $oopscount=0;
foreach my $key (keys(%hash)){
	#print $hash{$key}."\n";
	my @b=split("",$hash{$key});
	#if (scalar(@b)!=250){next;}
	if (scalar(@b)!=249){next;}
	my $temp1="";
	my $temp2="";
	my $count=0;
	for (my $x=0;$x<scalar(@ref);$x++){
		if ($ref[$x] eq "C"){
			if ($b[$x] eq "C"){
				$temp1=$temp1."1";
			}
			elsif ($b[$x] eq "T"){
				$temp1=$temp1."2";
			}
			else{
				$temp1=$temp1."9";
			}	
		}
		if ($ref[$x] eq "G"){
			if ($b[$x] eq "G"){
				$temp1=$temp1."4";
			}
			elsif ($b[$x] eq "A"){
				$temp1=$temp1."5";
			}
			else{
				$temp1=$temp1."7";
				#print "dfgfgggggggggggggggggggggggggggggggggggggggg\n";
			}	
		}
		if (($ref[$x] ne "C")&&($ref[$x] ne "G")){$temp1=$temp1."0";}
	}
	#print $count."\n";
	my @t=split("",$temp1);
	#print $t[1]."\t".$t[10]."\n";
	my $t=join("\t",@t);
	#print $t."\n";
	print OUT $t."\n";
}
close(OUT); 
print "END\n";
